### PR TITLE
Change URL for refresh

### PR DESCRIPTION
**Pull request by jennybc**
Motivated by #147 

I am very skeptical that this URL is the problem, but it is easy enough to do so, in case someone wants to see if this helps.

### CODE REVIEW

**Comment by SandorSzalma1** [comment]
Hi Jenny

Please excuse me, that it took so long.

I have tested this pull request in my environment and with this the access is working!
There is no more error in token_fetch() method.

Would you push this to master?

Thanks and Regards,
Sándor

**Comment by SandorSzalma1** [comment]
Hi Jenny, Hi Team,
would you merge this pull request into master, please?
Thanks and Regards,
Sándor

**Comment by SandorSzalma1** [comment]
Hi @jennybc 
I have tested it, it works, would you merge it into main?
Thank and Regards,
Sándor

**Comment by jennybc** [comment]
@SandorSzalma1 See #196, which is a more proper approach to updating our auth URIs.

**Pull request closed without merging**
